branches:
  only:
  - master
language: ruby
rvm:
- 1.9.3
notifications:
  email: false
before_script:
- git config --global user.name "xuehung"
- git config --global user.email "xuehung@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- rake setup_github_pages[$REPO_URL]
# To reset the 'url' to the custom domain in '_config.yml'
- git checkout -- _config.yml
# To deal with images
- ruby processimg.rb  
- git commit -a -m "[ci skip]"
script:
- set LANG=zh_TW.UTF-8
- set LC_ALL=zh_TW.UTF-8
- rake generate
after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
#- rake deploy
- git remote -v
- git push origin master
env:
  global:
  - GH_REPO="codefortomorrow/foodopendata"
  - secure: SPtYuqVW182Mu6uEGyA3+cui6FHro+VCH6/hJgKCxQna10hpC7182jvGzejgJG3Q4yy/1ZSiHgUCpFDpn13dxY9vfkhUm7UTDKk5qSsYcOyL1d/Eq2MAmeLDQu8faNlaXBzM+hWts27fwYAhEJyRPh+HOQnJdWJaZnh35H2mgnc=
