# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://food.codefortomorrow.org
title: 開放食庫Food Open Data
subtitle: 飲食革命，從認識你吃的食物開始。
author: Food Open Data
#simple_search: http://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
#subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]
# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user:
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false

# prose.io settings
# reference:
#   https://github.com/trunkclub/trunkclub.github.io/blob/source/_config.yml#L107-L148
prose:
  rooturl: "source/_posts"
  #media: "source/images/blog"
  metadata:
    "source/_posts": |
      layout: post
      published: true
      title: "Title"
      comment: true
      author: ""
      
#      - name: "layout"
#        field:
#          element: "hidden"
#          value: "post"
#      - name: "author"
#        field:
#          element: "text"
#          label: "Author"
#          value: ""
#          type: "text"
         

# team list
team:
  - position: Other
    member:
      - name: Chia-Kai Liu
        email: chiakai.liu@gmail.com

      - name: TH Schee
        email: info@motomosa.com

      - name: Ellis Wang
        position: Creatives
        email: elliswang@me.com
        imglink: https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash4/s160x160/487061_10151095026136207_955527267_a.jpg

      - name: Leo YANG
        email: yleader@gmail.com

      - name: 李易修
        position: Other
        email: lis186@gmail.com

      - name: 映竹
        position: Consumer
        email: jungheng@gmail.com
        imglink: https://lh5.googleusercontent.com/-i2HZEM7Xdno/AAAAAAAAAAI/AAAAAAAAbyk/EKkFcF9pHhI/s120-c/photo.jpg

  - position: Web Developer
    member:
      - name: Jimmy Huang

      - name: Mike Cheng
        email: xuehung@gmail.com

      - name: Evan Li
        email: jenghung@gmail.com
        imglink: https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-ash4/4897_98541187401_2842427_n.jpg

      - name: Nevin Chen
        email: cnevinc@livemail.tw

      - name: Klern Wang
        email: klern313@gmail.com    
  
  - position: Designer
    member:
      - name: 致遠
        email: woodesign61@gmail.com

      - name: 王崇政
        email: chungcheng09@gmail.com

      - name: Beti Chiang
        email: beti2004@gmail.com

  - position: App Developer
    member:
      - name: Chen Hao Lin
        email: georgelin422@gmail.com
        imglink: https://fbcdn-profile-a.akamaihd.net/hprofile-ak-prn2/c48.20.462.462/s160x160/1239047_10151688130452483_1027079699_n.jpg

      - name: Chun Wei Lee
        email: jessy1092@gmail.com
        imglink: https://fbcdn-profile-a.akamaihd.net/hprofile-ak-prn1/c1.352.462.462/s160x160/947265_601144659896241_181020200_n.jpg

      - name: Water Su
        email: pointou@gmail.com

      - name: 鄭鈞隆
        email: joanneandy1479@gmail.com
        imglink: https://lh3.googleusercontent.com/-0vAVHtzfRng/AAAAAAAAAAI/AAAAAAAAAL0/CVVKZ5BhlWE/s120-c/photo.jpg
